// This file is generated by `pnpm gen:api`. Until then, a placeholder
// `paths` type keeps openapi-fetch buildable. Run the API + `pnpm gen:api`
// to overwrite this file.
export type paths = Record<string, unknown>;
export type components = { schemas: Record<string, unknown> };
